### ISSUE TITLE
MacOS/Safari: Wrong download redirect on website

### ISSUE THREAD

**Issue by vrilcode** [keepassxreboot/keepassxc-org#113]
## Overview
Download page is redirecting to ARM64 binary of KeePassXC for MacOS instead of x86 version, if Safari is used.

## Steps to Reproduce
1.  Go to https://keepassxc.org/download/#macos with Safari under MacOS x86
2. Click on "DOWNLOAD FOR MACOS"
3. KeePassXC ARM64 version is downloaded

## Expected Behavior
It should download x86 version of KeePassXC. With Chrome (also MacOS x86) it's working. Maybe wrong analysis of user-agent string?

## Actual Behavior
It's downloading ARM64 version of KeePassXC.

## Context
Operating System: MacOS 13.1 (x86_64)
Browser: Safari 16

**Comment by droidmonkey** [comment]
@phoerious

**Comment by phoerious** [comment]
Looks like an unsolvable problem to me. Browsers on macOS do not report the CPU architecture in the user agent string.

Safari on macOS identifies itself as
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15
```
no matter whether it's a real "Intel" machine or "Apple Silicon". It works in Chrome, because Chrome supports the client hints API. However, Safari and Firefox don't support this API yet, so there is no way to determine the architecture.

**Comment by vrilcode** [comment]
Maybe it's possible to offer a selection for users instead of auto-redirect?

**Comment by phoerious** [comment]
You can always download the correct version for your device und "See more options"
